Discounted cost documentation
Multi-Energy-Systems-Optimization/mesido pull request #202
Opened 2024-11-06 13:02 UTC by jarsarasty

Small updates in the documentation.

Linked to issue #201

2025-01-23 11:34 UTC, KobusVanRooyen commented on docs/theory/financial.rst
> +    Cost_{installation} = C^{a}_{install} \delta^{a}_{aggr\_count}
Nice spot. Can you also update this in the asset sizing section 6.2, equation 6.5. Similarly update "single,max" to "singe_max"

2025-01-23 11:34 UTC, KobusVanRooyen commented on docs/theory/financial.rst
> +Assuming that the OPEX is already calculated on an annual basis, the annualized CAPEX is calculated using an EAC factor :math:`F_{a}`. This factor is computed as based on a discount rate (as an annua
I am not sure what this has to do with the discounted CAPEX ? "Assuming that the OPEX is already calculated on an annual basis" ?

2025-01-23 11:34 UTC, KobusVanRooyen commented on docs/theory/financial.rst
> +   F_{a} =
Please add an equation number

2025-01-23 11:34 UTC, KobusVanRooyen commented on docs/theory/financial.rst
> +   \frac{1}{n} & \text{if } r = 0 \\
Maybe add an equation showing how the EAC is calculated something like Cost_CEA = (Cost_installation +.... ) * F_a. Which is the annual cost ....

2025-02-13 08:25 UTC, jarsarasty commented on docs/theory/financial.rst
> +   \frac{1}{n} & \text{if } r = 0 \\
The equation has been added and the explanation of some cost elements has been adjusted to make it clear that this factor applies only to CAPEX.

2025-02-13 08:25 UTC, jarsarasty commented on docs/theory/financial.rst
> +Assuming that the OPEX is already calculated on an annual basis, the annualized CAPEX is calculated using an EAC factor :math:`F_{a}`. This factor is computed as based on a discount rate (as an annua
I have tried to make the explanation a bit clearer. 
Please see the new section 5.2 Total Cost Calculation and the revised section 5.3 Annualized Discounted Cost Calculation.

2025-02-13 08:25 UTC, jarsarasty commented on docs/theory/Workflows.rst
>      * This assumptions is sufficient when the user is still in a phase where the exact location of (booster-)pumps is to be determined and hence limiting the sizing of pipes with pressure drop calcul
Thanks for pointing this out. 
I will then create a new pull request for a merge to patch_dtk

2025-02-13 08:29 UTC, jarsarasty commented on docs/theory/Workflows.rst
>      * This assumptions is sufficient when the user is still in a phase where the exact location of (booster-)pumps is to be determined and hence limiting the sizing of pipes with pressure drop calcul
Done

2025-02-17 16:54 UTC, KobusVanRooyen approved these changes

2025-02-17 16:54 UTC, KobusVanRooyen commented on docs/theory/financial.rst
> +   F_{a} =
It is fine as is then. Thanks for the feedback

2025-02-17 16:54 UTC, KobusVanRooyen commented on docs/theory/financial.rst
> +   \frac{1}{n} & \text{if } r = 0 \\
Nice

2025-02-17 16:58 UTC, KobusVanRooyen commented on docs/theory/Workflows.rst
>      * Note that EndScenarioSizingHeadLoss can be used when the user wants the pressure drop functionality.
Please update the changelog

2025-02-17 16:59 UTC, KobusVanRooyen commented
@jarsarasty once the changelog has been updated it can be approved

2025-02-18 10:27 UTC, jarsarasty commented on docs/theory/Workflows.rst
>      * Note that EndScenarioSizingHeadLoss can be used when the user wants the pressure drop functionality.
Hi @KobusVan, 
I pulled the changelog from patch_dtk and updated the 
changelog with changes to the Financial section
of the documentation. Please let me know if the version number should be different or if other changes are needed.

2025-02-19 13:14 UTC, KobusVanRooyen requested changes

2025-02-20 13:45 UTC, jarsarasty commented on CHANGELOG.md
> +# [0.1.8.6] - 2025-02-18
@KobusVanRooyen, it should be Ok, now. Please check

2025-02-21 09:13 UTC, KobusVanRooyen approved these changes

2025-02-24 09:08 UTC, merged